language: objective-c
before_install:
  - brew update
  - brew reinstall xctool
  - gem update cocoapods
xcode_workspace: eventually.xcworkspace
xcode_scheme: eventually
xcode_sdk:
  - iphonesimulator7.0
  - iphonesimulator7.1
